Tabs to spaces + pug optimization + some small fixes

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -1,6 +1,6 @@
 #!/bin/sh
 
 if ! npm run lint ; then
-	echo "Lint errors found. Aborting commit."
-	exit 1
+  echo "Lint errors found. Aborting commit."
+  exit 1
 fi
