Removed Husky - added native git pre-commit

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -1,3 +1,6 @@
 #!/bin/sh
 
-npm run lint
+if ! npm run lint ; then
+	echo "Lint errors found. Aborting commit."
+	exit 1
+fi
